-- Populate tabla clientes
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Yvan', 'Lopez', 'yvan@mail.com', '2023-01-19');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Benjamin', 'Rivera', 'benjamin@mail.com', '2022-01-19');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Maritza', 'Tiburcio', 'maritza@mail.com', '2021-11-20');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Fausto', 'De La Cruz', 'fausto@mail.com', '2020-10-18');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Eber', 'Ruiz', 'eber@mail.com', '2019-09-17');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Maria', 'Rivera', 'maria@mail.com', '2018-08-16');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Silvana', 'Banana', 'silvana@mail.com', '2017-07-15');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Eva', 'Constancia', 'eva@mail.com', '2016-06-14');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Segundo', 'Cerna', 'segundo@mail.com', '2015-05-13');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Ricardo', 'Oviedo', 'ricardo@mail.com', '2014-04-12');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Jose', 'Guanilo', 'jose@mail.com', '2013-03-11');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Luis', 'Carrasco', 'luis@mail.com', '2012-02-10');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Roberto', 'Gomez', 'user1@mail.com', '2007-01-19');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Mery', 'Xmas', 'user2@mail.com', '2006-01-19');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Raul', 'Romero', 'user3@mail.com', '2005-11-20');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Edinson', 'Flores', 'user4@mail.com', '2006-10-18');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Malena', 'Diaz', 'user5@mail.com', '2004-09-17');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Eva', 'Longoria', 'user6@mail.com', '2003-08-16');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Antonia', 'Nieves', 'user7@mail.com', '2008-07-15');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Glicerio', 'Tamayo', 'user8@mail.com', '2001-06-14');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Manuel', 'Bell', 'user9@mail.com', '1982-05-13');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Cesar', 'Lomas', 'user10@mail.com', '1985-04-12');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Sergio', 'Ramirez', 'user11@mail.com', '1952-03-11');
INSERT INTO clientes(nombre, apellido, email, created_at) VALUES('Leoncio', 'Villa', 'user12@mail.com', '1981-02-10');

insert into clientes (nombre, apellido, email, created_at) values ('Vin', 'Burnand', 'vburnand0@columbia.edu', '2022-08-08');
insert into clientes (nombre, apellido, email, created_at) values ('Codie', 'Bazley', 'cbazley1@pinterest.com', '2022-11-20');
insert into clientes (nombre, apellido, email, created_at) values ('Joelle', 'de Clercq', 'jdeclercq2@taobao.com', '2022-05-28');
insert into clientes (nombre, apellido, email, created_at) values ('Rod', 'Landsman', 'rlandsman3@google.nl', '2022-10-13');
insert into clientes (nombre, apellido, email, created_at) values ('Rolfe', 'Stivers', 'rstivers4@shutterfly.com', '2022-06-08');
insert into clientes (nombre, apellido, email, created_at) values ('Alejoa', 'Alecock', 'aalecock5@phoca.cz', '2023-02-11');
insert into clientes (nombre, apellido, email, created_at) values ('Miranda', 'Forshaw', 'mforshaw6@angelfire.com', '2022-03-13');
insert into clientes (nombre, apellido, email, created_at) values ('Nixie', 'Nutbrown', 'nnutbrown7@blogspot.com', '2022-08-26');
insert into clientes (nombre, apellido, email, created_at) values ('Oren', 'Aisman', 'oaisman8@instagram.com', '2022-03-01');
insert into clientes (nombre, apellido, email, created_at) values ('Romola', 'Gissing', 'rgissing9@taobao.com', '2022-06-27');
insert into clientes (nombre, apellido, email, created_at) values ('Sebastian', 'Lockless', 'slocklessa@live.com', '2022-05-25');
insert into clientes (nombre, apellido, email, created_at) values ('Manda', 'Germain', 'mgermainb@live.com', '2022-04-08');
insert into clientes (nombre, apellido, email, created_at) values ('Sholom', 'Borsnall', 'sborsnallc@naver.com', '2022-06-20');
insert into clientes (nombre, apellido, email, created_at) values ('Emerson', 'Saker', 'esakerd@hhs.gov', '2022-06-30');
insert into clientes (nombre, apellido, email, created_at) values ('Britta', 'Delamar', 'bdelamare@wikipedia.org', '2022-12-10');
insert into clientes (nombre, apellido, email, created_at) values ('Terence', 'Petrussi', 'tpetrussif@pen.io', '2022-03-09');
insert into clientes (nombre, apellido, email, created_at) values ('Tann', 'Ainley', 'tainleyg@devhub.com', '2023-01-13');
insert into clientes (nombre, apellido, email, created_at) values ('Gayelord', 'O''Kieran', 'gokieranh@ucoz.com', '2022-08-13');
insert into clientes (nombre, apellido, email, created_at) values ('Kellsie', 'Cordeau', 'kcordeaui@abc.net.au', '2022-10-15');
insert into clientes (nombre, apellido, email, created_at) values ('Judas', 'Wincer', 'jwincerj@bloglovin.com', '2022-04-29');
insert into clientes (nombre, apellido, email, created_at) values ('Virgil', 'Widdowson', 'vwiddowsonk@over-blog.com', '2022-08-13');
insert into clientes (nombre, apellido, email, created_at) values ('Debbie', 'Ruggiero', 'druggierol@eepurl.com', '2022-06-25');
insert into clientes (nombre, apellido, email, created_at) values ('Paddy', 'Orrell', 'porrellm@scribd.com', '2022-04-28');
insert into clientes (nombre, apellido, email, created_at) values ('Glori', 'De Anesy', 'gdeanesyn@usa.gov', '2022-11-11');
insert into clientes (nombre, apellido, email, created_at) values ('Teddie', 'Whitaker', 'twhitakero@paypal.com', '2022-08-04');
insert into clientes (nombre, apellido, email, created_at) values ('Elsworth', 'Spaughton', 'espaughtonp@cmu.edu', '2022-10-05');
insert into clientes (nombre, apellido, email, created_at) values ('Skippy', 'Scarce', 'sscarceq@nature.com', '2022-04-16');
insert into clientes (nombre, apellido, email, created_at) values ('Jervis', 'Trinkwon', 'jtrinkwonr@i2i.jp', '2023-02-20');
insert into clientes (nombre, apellido, email, created_at) values ('Herculie', 'Mustill', 'hmustills@fema.gov', '2022-12-05');
insert into clientes (nombre, apellido, email, created_at) values ('Nissa', 'Yepiskov', 'nyepiskovt@economist.com', '2023-01-02');
insert into clientes (nombre, apellido, email, created_at) values ('Marika', 'Issakov', 'missakovu@theglobeandmail.com', '2022-10-26');
insert into clientes (nombre, apellido, email, created_at) values ('Mufi', 'Winmill', 'mwinmillv@i2i.jp', '2022-11-13');
insert into clientes (nombre, apellido, email, created_at) values ('Niel', 'Weddeburn', 'nweddeburnw@msn.com', '2022-09-02');
insert into clientes (nombre, apellido, email, created_at) values ('Casandra', 'Cordner', 'ccordnerx@bbb.org', '2022-10-24');
insert into clientes (nombre, apellido, email, created_at) values ('Evan', 'Fessler', 'efesslery@wunderground.com', '2023-02-07');
insert into clientes (nombre, apellido, email, created_at) values ('Rodd', 'Broadbent', 'rbroadbentz@bigcartel.com', '2022-09-27');
insert into clientes (nombre, apellido, email, created_at) values ('Sergei', 'Corzon', 'scorzon10@quantcast.com', '2023-01-14');
insert into clientes (nombre, apellido, email, created_at) values ('Aldus', 'Mc Dermid', 'amcdermid11@dion.ne.jp', '2022-03-02');
insert into clientes (nombre, apellido, email, created_at) values ('Florentia', 'Redsull', 'fredsull12@tripod.com', '2023-02-01');
insert into clientes (nombre, apellido, email, created_at) values ('Cleve', 'Kivlehan', 'ckivlehan13@over-blog.com', '2022-07-13');
insert into clientes (nombre, apellido, email, created_at) values ('Cly', 'Pepperell', 'cpepperell14@harvard.edu', '2022-09-08');
insert into clientes (nombre, apellido, email, created_at) values ('Codee', 'Hallin', 'challin15@netlog.com', '2022-11-19');
insert into clientes (nombre, apellido, email, created_at) values ('Sam', 'Mallender', 'smallender16@sina.com.cn', '2023-01-10');
insert into clientes (nombre, apellido, email, created_at) values ('Chelsie', 'Thunder', 'cthunder17@yolasite.com', '2022-04-23');
insert into clientes (nombre, apellido, email, created_at) values ('Annnora', 'Fraczkiewicz', 'afraczkiewicz18@diigo.com', '2022-03-31');
insert into clientes (nombre, apellido, email, created_at) values ('Brock', 'Ferens', 'bferens19@ifeng.com', '2022-08-28');
insert into clientes (nombre, apellido, email, created_at) values ('Jeanelle', 'Dowtry', 'jdowtry1a@hhs.gov', '2023-01-29');
insert into clientes (nombre, apellido, email, created_at) values ('Wendie', 'Vooght', 'wvooght1b@posterous.com', '2022-04-27');
insert into clientes (nombre, apellido, email, created_at) values ('Beale', 'Wisher', 'bwisher1c@delicious.com', '2023-02-21');
insert into clientes (nombre, apellido, email, created_at) values ('Huntington', 'Rodgerson', 'hrodgerson1d@amazonaws.com', '2023-02-04');
insert into clientes (nombre, apellido, email, created_at) values ('Anthe', 'Assandri', 'aassandri1e@skype.com', '2022-05-13');
insert into clientes (nombre, apellido, email, created_at) values ('Arnold', 'Hindge', 'ahindge1f@zdnet.com', '2023-01-14');
insert into clientes (nombre, apellido, email, created_at) values ('Alair', 'Mossop', 'amossop1g@twitpic.com', '2023-02-15');
insert into clientes (nombre, apellido, email, created_at) values ('Papagena', 'Dubock', 'pdubock1h@ovh.net', '2022-12-28');
insert into clientes (nombre, apellido, email, created_at) values ('Humphrey', 'Blench', 'hblench1i@t.co', '2022-04-22');
insert into clientes (nombre, apellido, email, created_at) values ('Darbie', 'Das', 'ddas1j@ucoz.ru', '2022-03-27');
insert into clientes (nombre, apellido, email, created_at) values ('Tabbi', 'Renol', 'trenol1k@va.gov', '2023-01-15');
insert into clientes (nombre, apellido, email, created_at) values ('Mina', 'Rubbens', 'mrubbens1l@geocities.jp', '2022-10-26');
insert into clientes (nombre, apellido, email, created_at) values ('Sari', 'Dineges', 'sdineges1m@purevolume.com', '2022-12-17');
insert into clientes (nombre, apellido, email, created_at) values ('Nelle', 'Instone', 'ninstone1n@friendfeed.com', '2022-10-28');
insert into clientes (nombre, apellido, email, created_at) values ('Monroe', 'Kirley', 'mkirley1o@fastcompany.com', '2022-06-21');
insert into clientes (nombre, apellido, email, created_at) values ('Kristo', 'Ranner', 'kranner1p@mlb.com', '2023-02-22');
insert into clientes (nombre, apellido, email, created_at) values ('Jaclin', 'Vasyagin', 'jvasyagin1q@liveinternet.ru', '2022-03-09');
insert into clientes (nombre, apellido, email, created_at) values ('Mab', 'Allbut', 'mallbut1r@de.vu', '2022-08-19');
insert into clientes (nombre, apellido, email, created_at) values ('Kit', 'Aulds', 'kaulds1s@seesaa.net', '2022-09-02');
insert into clientes (nombre, apellido, email, created_at) values ('Jill', 'Lockhurst', 'jlockhurst1t@miitbeian.gov.cn', '2022-08-29');
insert into clientes (nombre, apellido, email, created_at) values ('Vinson', 'Scintsbury', 'vscintsbury1u@facebook.com', '2022-09-23');
insert into clientes (nombre, apellido, email, created_at) values ('Ermanno', 'Seatter', 'eseatter1v@washingtonpost.com', '2022-08-03');
insert into clientes (nombre, apellido, email, created_at) values ('Betti', 'Boord', 'bboord1w@acquirethisname.com', '2022-10-02');
insert into clientes (nombre, apellido, email, created_at) values ('Denni', 'Rowley', 'drowley1x@apple.com', '2022-10-06');
insert into clientes (nombre, apellido, email, created_at) values ('Zarah', 'Collman', 'zcollman1y@msn.com', '2022-07-01');
insert into clientes (nombre, apellido, email, created_at) values ('Davina', 'Dulwich', 'ddulwich1z@independent.co.uk', '2022-07-20');
insert into clientes (nombre, apellido, email, created_at) values ('Anjela', 'Marson', 'amarson20@desdev.cn', '2022-12-30');
insert into clientes (nombre, apellido, email, created_at) values ('Alyce', 'Jopson', 'ajopson21@yahoo.co.jp', '2022-07-18');